//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYD_COPY_FILE {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int arr_data_type {
            get {
                return ((int)(this["arr_data_type"]));
            }
            set {
                this["arr_data_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int arr_font_type {
            get {
                return ((int)(this["arr_font_type"]));
            }
            set {
                this["arr_font_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int arr_fun_sel {
            get {
                return ((int)(this["arr_fun_sel"]));
            }
            set {
                this["arr_fun_sel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string arr_source_file_text {
            get {
                return ((string)(this["arr_source_file_text"]));
            }
            set {
                this["arr_source_file_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string arr_extract_len {
            get {
                return ((string)(this["arr_extract_len"]));
            }
            set {
                this["arr_extract_len"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string source_copyfile_textBox {
            get {
                return ((string)(this["source_copyfile_textBox"]));
            }
            set {
                this["source_copyfile_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string destination_file_textBox {
            get {
                return ((string)(this["destination_file_textBox"]));
            }
            set {
                this["destination_file_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string destination_file_textBox_two {
            get {
                return ((string)(this["destination_file_textBox_two"]));
            }
            set {
                this["destination_file_textBox_two"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBox_copy_destinationfileend {
            get {
                return ((string)(this["textBox_copy_destinationfileend"]));
            }
            set {
                this["textBox_copy_destinationfileend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string source_copyfile_textBox_sync {
            get {
                return ((string)(this["source_copyfile_textBox_sync"]));
            }
            set {
                this["source_copyfile_textBox_sync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string destination_file_textBox_sync {
            get {
                return ((string)(this["destination_file_textBox_sync"]));
            }
            set {
                this["destination_file_textBox_sync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string destination_file_textBox_two_sync {
            get {
                return ((string)(this["destination_file_textBox_two_sync"]));
            }
            set {
                this["destination_file_textBox_two_sync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBox_copy_destinationfileend_sync {
            get {
                return ((string)(this["textBox_copy_destinationfileend_sync"]));
            }
            set {
                this["textBox_copy_destinationfileend_sync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBox_key {
            get {
                return ((string)(this["textBox_key"]));
            }
            set {
                this["textBox_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pictureBox_interface_ismin {
            get {
                return ((bool)(this["pictureBox_interface_ismin"]));
            }
            set {
                this["pictureBox_interface_ismin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_textBox_section1 {
            get {
                return ((string)(this["Setting_textBox_section1"]));
            }
            set {
                this["Setting_textBox_section1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_textBox_section2 {
            get {
                return ((string)(this["Setting_textBox_section2"]));
            }
            set {
                this["Setting_textBox_section2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_textBox_section3 {
            get {
                return ((string)(this["Setting_textBox_section3"]));
            }
            set {
                this["Setting_textBox_section3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_textBox_section4 {
            get {
                return ((string)(this["Setting_textBox_section4"]));
            }
            set {
                this["Setting_textBox_section4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_textBox_section5 {
            get {
                return ((string)(this["Setting_textBox_section5"]));
            }
            set {
                this["Setting_textBox_section5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_textBox_section6 {
            get {
                return ((string)(this["Setting_textBox_section6"]));
            }
            set {
                this["Setting_textBox_section6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_source_copyfile_textBox_rename {
            get {
                return ((string)(this["Setting_source_copyfile_textBox_rename"]));
            }
            set {
                this["Setting_source_copyfile_textBox_rename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_source_copyfile_prefix_textBox_rename {
            get {
                return ((string)(this["Setting_source_copyfile_prefix_textBox_rename"]));
            }
            set {
                this["Setting_source_copyfile_prefix_textBox_rename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_source_copyfile_suffix_textBox_rename {
            get {
                return ((string)(this["Setting_source_copyfile_suffix_textBox_rename"]));
            }
            set {
                this["Setting_source_copyfile_suffix_textBox_rename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_checkBox10 {
            get {
                return ((bool)(this["Setting_checkBox10"]));
            }
            set {
                this["Setting_checkBox10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_checkBox_systemtime_rename {
            get {
                return ((bool)(this["Setting_checkBox_systemtime_rename"]));
            }
            set {
                this["Setting_checkBox_systemtime_rename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_checkBox6 {
            get {
                return ((bool)(this["Setting_checkBox6"]));
            }
            set {
                this["Setting_checkBox6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int rename_mode_sel {
            get {
                return ((int)(this["rename_mode_sel"]));
            }
            set {
                this["rename_mode_sel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_checkBox_delete_srcfile {
            get {
                return ((bool)(this["Setting_checkBox_delete_srcfile"]));
            }
            set {
                this["Setting_checkBox_delete_srcfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\HP\\Desktop")]
        public string Setting_textBoxSaveDir {
            get {
                return ((string)(this["Setting_textBoxSaveDir"]));
            }
            set {
                this["Setting_textBoxSaveDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line1 {
            get {
                return ((string)(this["suffix_textBox_rename_line1"]));
            }
            set {
                this["suffix_textBox_rename_line1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line2 {
            get {
                return ((string)(this["suffix_textBox_rename_line2"]));
            }
            set {
                this["suffix_textBox_rename_line2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line3 {
            get {
                return ((string)(this["suffix_textBox_rename_line3"]));
            }
            set {
                this["suffix_textBox_rename_line3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line4 {
            get {
                return ((string)(this["suffix_textBox_rename_line4"]));
            }
            set {
                this["suffix_textBox_rename_line4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line5 {
            get {
                return ((string)(this["suffix_textBox_rename_line5"]));
            }
            set {
                this["suffix_textBox_rename_line5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line6 {
            get {
                return ((string)(this["suffix_textBox_rename_line6"]));
            }
            set {
                this["suffix_textBox_rename_line6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line7 {
            get {
                return ((string)(this["suffix_textBox_rename_line7"]));
            }
            set {
                this["suffix_textBox_rename_line7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line8 {
            get {
                return ((string)(this["suffix_textBox_rename_line8"]));
            }
            set {
                this["suffix_textBox_rename_line8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line9 {
            get {
                return ((string)(this["suffix_textBox_rename_line9"]));
            }
            set {
                this["suffix_textBox_rename_line9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string suffix_textBox_rename_line10 {
            get {
                return ((string)(this["suffix_textBox_rename_line10"]));
            }
            set {
                this["suffix_textBox_rename_line10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 设置 {
            get {
                return ((string)(this["设置"]));
            }
            set {
                this["设置"] = value;
            }
        }
    }
}
