# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 208)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tabWidgetTools = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetTools.setEnabled(True)
        self.tabWidgetTools.setObjectName("tabWidgetTools")
        self.tabFile = QtWidgets.QWidget()
        self.tabFile.setObjectName("tabFile")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabFile)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEditSrcFilePath_0 = MyQLineEdit(self.tabFile)
        self.lineEditSrcFilePath_0.setObjectName("lineEditSrcFilePath_0")
        self.horizontalLayout_19.addWidget(self.lineEditSrcFilePath_0)
        self.pushButtonFileOpen = QtWidgets.QPushButton(self.tabFile)
        self.pushButtonFileOpen.setObjectName("pushButtonFileOpen")
        self.horizontalLayout_19.addWidget(self.pushButtonFileOpen)
        self.verticalLayout_17.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditTargetFilePath_0 = MyQLineEdit(self.tabFile)
        self.lineEditTargetFilePath_0.setObjectName("lineEditTargetFilePath_0")
        self.horizontalLayout_6.addWidget(self.lineEditTargetFilePath_0)
        self.pushButtonFolderOpen = QtWidgets.QPushButton(self.tabFile)
        self.pushButtonFolderOpen.setObjectName("pushButtonFolderOpen")
        self.horizontalLayout_6.addWidget(self.pushButtonFolderOpen)
        self.verticalLayout_17.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_17)
        self.pushButtonConvertPicture = QtWidgets.QPushButton(self.tabFile)
        self.pushButtonConvertPicture.setObjectName("pushButtonConvertPicture")
        self.verticalLayout.addWidget(self.pushButtonConvertPicture)
        self.tabWidgetTools.addTab(self.tabFile, "")
        self.verticalLayout_18.addWidget(self.tabWidgetTools)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetTools.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonFileOpen.setText(_translate("MainWindow", "选择图片目录"))
        self.pushButtonFolderOpen.setText(_translate("MainWindow", "选择目标目录"))
        self.pushButtonConvertPicture.setText(_translate("MainWindow", "批量图片转换成24位BMP"))
        self.tabWidgetTools.setTabText(self.tabWidgetTools.indexOf(self.tabFile), _translate("MainWindow", "Picture"))
from MyWidget import MyQLineEdit
